import re
import regex

# region Patterns
ABBREVIATION_TOKEN_PATTERN = r"[\p{L}\p{N}][\p{Lu}\p{N}]*"
LINK_STRING_DELIMITER_PATTERN = r"\:\:"
PROPERTY_STRING_DELIMITER_PATTERN = r"\:"
RELATED_SUBJECT_STRING_DELIMITER_PATTERN = r"\:"
SHORT_ABBREVIATION_TOKEN_PATTERN = r"[\p{L}\p{N}]{1,3}[\p{Lu}\p{N}]*"
UNICODE_ALPHA_PATTERN = r"\p{L}+"
WHITESPACE_PATTERN = r"\s+"

# endregion

# region RegEx
ABBREVIATION_TOKEN_REGEX = regex.compile(ABBREVIATION_TOKEN_PATTERN)
LINK_STRING_DELIMITER_REGEX = re.compile(LINK_STRING_DELIMITER_PATTERN)
PROPERTY_STRING_DELIMITER_REGEX = re.compile(PROPERTY_STRING_DELIMITER_PATTERN)
RELATED_SUBJECT_STRING_DELIMITER_REGEX = re.compile(
    RELATED_SUBJECT_STRING_DELIMITER_PATTERN
)
SHORT_ABBREVIATION_TOKEN_REGEX = regex.compile(SHORT_ABBREVIATION_TOKEN_PATTERN)
UNICODE_ALPHA_REGEX = regex.compile(UNICODE_ALPHA_PATTERN)
WHITESPACE_REGEX = re.compile(WHITESPACE_PATTERN)

# endregion
